spring.application.name=demo-mock

scanrest.enabled=true
scanrest.mode=MOCKMVC
scanrest.run-on-startup=false

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.com.yubraj.test.scanrest=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
