spring.application.name=demo

scanrest.enabled=true
scanrest.mode=LIVE
scanrest.run-on-startup=true


logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.com.yubraj.test.scanrest=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
